spring:
  application:
    name: backend_test

#  properties:
#    active: dev
# Ezt én közvetlenül az IntelliJ-ben állítottam be, hogy az aktív profil legyen, de itt is van rá lehetőség

server:
  port: 8080
